/* Shared header: one template controls every website page. */
const sharedHeader="<header class=\"site-header\"><a class=\"brand\" href=\"index.html\" aria-label=\"MQA+ Home\"><img class=\"header-org-logo\" src=\"MQA%20Logo.JPEG\" alt=\"MQA+\"></a><button class=\"menu\" aria-expanded=\"false\" aria-controls=\"site-navigation\">Menu</button><nav id=\"site-navigation\"><a href=\"about.html\">About</a><a href=\"programs.html\">Programs</a><a href=\"initiatives.html\">Initiatives</a><a href=\"community-groups.html\">Community Groups</a><a href=\"events.html\">Events</a><a href=\"resources.html\">Resources</a><a href=\"get-involved.html\">Get Involved</a><a href=\"shop.html\">Shop</a><a href=\"contact.html\">Contact</a></nav><div class=\"top-actions\"><a class=\"btn outline\" href=\"get-involved.html\">Become a Member</a><a class=\"btn pink\" href=\"#\" data-zeffy-donate>Donate</a></div></header>";
const existingHeader=document.querySelector('header.site-header');
if(existingHeader)existingHeader.outerHTML=sharedHeader;
const b=document.querySelector('.menu'),n=document.querySelector('nav');if(b&&n)b.addEventListener('click',()=>{const o=n.classList.toggle('open');b.setAttribute('aria-expanded',o)});document.querySelectorAll('.details').forEach(x=>x.addEventListener('click',()=>document.getElementById(x.dataset.modal)?.showModal()));document.querySelectorAll('dialog .close').forEach(x=>x.addEventListener('click',()=>x.closest('dialog').close()));const ef=document.querySelectorAll('.filter');ef.forEach(x=>x.addEventListener('click',()=>{ef.forEach(y=>y.classList.remove('active'));x.classList.add('active');document.querySelectorAll('.event-large').forEach(c=>c.hidden=x.dataset.filter!=='all'&&!c.dataset.cat.includes(x.dataset.filter))}));const rf=document.querySelectorAll('.resource-filter'),rs=document.getElementById('resource-search');function resources(){const cat=document.querySelector('.resource-filter.active')?.dataset.filter||'all',q=(rs?.value||'').toLowerCase();document.querySelectorAll('.resource-card').forEach(c=>c.hidden=(cat!=='all'&&!c.dataset.cat.includes(cat))||!(c.dataset.name+' '+c.innerText).toLowerCase().includes(q))}rf.forEach(x=>x.addEventListener('click',()=>{rf.forEach(y=>y.classList.remove('active'));x.classList.add('active');resources()}));rs?.addEventListener('input',resources);
/* Zeffy donation popup */
const zeffyFormUrl="https://www.zeffy.com/embed/donation-form/5b4d6203-da8c-4e39-a1d3-7c47722b6d53";
function openZeffyDonation(e){e?.preventDefault();const requestedForm=e?.currentTarget?.dataset?.zeffyForm||zeffyFormUrl;let d=document.getElementById("zeffy-donation-modal");if(!d){d=document.createElement("dialog");d.id="zeffy-donation-modal";d.style.cssText="width:min(94vw,760px);height:min(90vh,820px);padding:0;border:0;border-radius:18px;box-shadow:0 20px 70px #0007;overflow:hidden";d.innerHTML='<button type="button" aria-label="Close donation form" style="position:absolute;z-index:2;right:12px;top:10px;width:38px;height:38px;border:0;border-radius:50%;background:#fff;font-size:25px;cursor:pointer">×</button><iframe title="Donation form powered by Zeffy" src="'+zeffyFormUrl+'" style="border:0;width:100%;height:100%;display:block" allow="payment *"></iframe>';document.body.appendChild(d);d.querySelector("button").addEventListener("click",()=>d.close());d.addEventListener("click",x=>{if(x.target===d)d.close()});}const frame=d.querySelector("iframe");if(frame&&frame.src!==requestedForm)frame.src=requestedForm;d.showModal();}
document.querySelectorAll('a[href="https://www.zeffy.com/en-US/donation-form/5b4d6203-da8c-4e39-a1d3-7c47722b6d53"],[data-zeffy-donate]').forEach(a=>{a.removeAttribute("target");a.removeAttribute("rel");a.setAttribute("href","#");a.addEventListener("click",openZeffyDonation);});
